version: 3

services:
  dev:
    image: mcr.microsoft.com/devcontainers/universal:2
    command: sleep infinity
    network_mode: host
    depends_on:
      db

  db:
    network_mode: host
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: